version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: nyc_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: nyc_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:latest
    container_name: nyc_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db
    volumes:
      - mbdata:/metabase

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: nyc_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
  mbdata:

